env:
  es2021: true
  node: true
  browser: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  "no-underscore-dangle": 'off',
  "import/extensions": 0,
  import/no-extraneous-dependencies: 
    error,
    devDependencies: 0
}
